title: Deep Lighting Environment Map Estimation from Spherical Panoramas
description: 
show_downloads: true
theme: jekyll-theme-cayman

github:
    model_url: https://github.com/VCL3D/DeepPanoramaLighting
    repository_url: https://github.com/VCL3D/DeepPanoramaLighting
    is_project_page: true
    repository_name: DeepPanoramaLighting
    owner_url: https://github.com/VasilisGks
    owner_name: Vasilis Gkitsas
    
google_analytics: UA-147231916-1
